spring:
  application:
    name: zuul
server:
  port: 7070
zuul:
  routes:
    reporter:
      url: 'http://localhost:7071/'
eureka:
  client:
    service‐url:
      defaultZone: http://localhost:7079/eureka
  instance:
    prefer‐ip‐address: true  #访问路径可以显示ip地址
    instance-id: USER-SERVICE   #自定义服务名称
management:
  endpoints:
    web:
      exposure:
        include: "*"  #因为springboot2.1必须加上,支持访问/actuator/hystrix.stream
