spring:
  application:
    name: zuul
  redis:
    host: localhost
    port: 6379
server:
  port: 7070
zuul:
  routes:
    reporter:
      path: /
      serviceId: REPORTER
    author:
      serviceId: AUTHOR
  sensitive-headers:

eureka:
  client:
    service‐url:
      defaultZone: http://localhost:7079/eureka
  instance:
    prefer‐ip‐address: true  #访问路径可以显示ip地址
    instance-id: USER-SERVICE   #自定义服务名称
management:
  endpoints:
    web:
      exposure:
        include: "*"  #因为springboot2.1必须加上,支持访问/actuator/hystrix.stream
logging:
  level:
    me: debug